name: Release

on:
  push:
    branches:
      - release

jobs:
  build:
    strategy:
      matrix:
        platform: [macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    defaults:
      run:
        working-directory: desktop

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Tauri Build
        uses: tauri-apps/tauri-action@v0
        with:
          projectPath: desktop
          distPath: dist
          tauriScript: ""
          args: "--target ${{ matrix.platform == 'windows-latest' && 'x86_64-pc-windows-msvc' || '' }}"
          tagName: v__VERSION__
          releaseName: 'v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
        env:
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
